// Generated by gencpp from file f1tenrh_msgs/SupplierStatus.msg
// DO NOT EDIT!


#ifndef F1TENRH_MSGS_MESSAGE_SUPPLIERSTATUS_H
#define F1TENRH_MSGS_MESSAGE_SUPPLIERSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace f1tenrh_msgs
{
template <class ContainerAllocator>
struct SupplierStatus_
{
  typedef SupplierStatus_<ContainerAllocator> Type;

  SupplierStatus_()
    : status(0)  {
    }
  SupplierStatus_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;



  enum {
    CLOSE = 0u,
    PREPARING = 1u,
    SUPPLYING = 2u,
  };


  typedef boost::shared_ptr< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SupplierStatus_

typedef ::f1tenrh_msgs::SupplierStatus_<std::allocator<void> > SupplierStatus;

typedef boost::shared_ptr< ::f1tenrh_msgs::SupplierStatus > SupplierStatusPtr;
typedef boost::shared_ptr< ::f1tenrh_msgs::SupplierStatus const> SupplierStatusConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace f1tenrh_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'f1tenrh_msgs': ['/home/ycz/f1tenth_ws/devel/share/f1tenrh_msgs/msg', '/home/ycz/f1tenth_ws/src/f1tenth_msgs/msg', '/home/ycz/f1tenth_ws/src/f1tenth_msgs/msg/referee_system']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81f3d032e85b689acf259876e6f8d051";
  }

  static const char* value(const ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81f3d032e85b689aULL;
  static const uint64_t static_value2 = 0xcf259876e6f8d051ULL;
};

template<class ContainerAllocator>
struct DataType< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1tenrh_msgs/SupplierStatus";
  }

  static const char* value(const ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#supplier status\n\
uint8 CLOSE = 0\n\
uint8 PREPARING = 1\n\
uint8 SUPPLYING = 2\n\
uint8 status\n\
\n\
";
  }

  static const char* value(const ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SupplierStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::f1tenrh_msgs::SupplierStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // F1TENRH_MSGS_MESSAGE_SUPPLIERSTATUS_H
